//! Adwaita theme tokens and style provider.

mod error;
#[cfg(test)]
mod tests;
/// Typed Adwaita design tokens generated by `spectrum-theme`.
pub mod tokens;

/// Embedded Adwaita light theme.
pub const ADWAITA_LIGHT_TOML: &str = include_str!("../themes/adwaita-light.toml");

pub use error::ThemeLoadError;
pub use tokens::ThemePack;
