//! Adwaita theme tokens and style provider.

mod error;
pub(crate) mod interpolate;
#[cfg(test)]
mod tests;
/// Typed Adwaita design tokens generated by `spectrum-theme`.
pub mod tokens;

/// Embedded Adwaita light theme.
pub const ADWAITA_LIGHT_TOML: &str = include_str!("../themes/adwaita-light.toml");
/// Embedded Adwaita dark theme.
pub const ADWAITA_DARK_TOML: &str = include_str!("../themes/adwaita-dark.toml");

pub use error::ThemeLoadError;
pub use tokens::ThemePack;
