[meta]
name = "Adwaita Light"
mode = "light"
author = "GNOME libadwaita reference values"
version = "0.1.0"
description = "Adwaita light colors used by currently implemented Iced Adwaita components."

[app.window]
bg = "#fafafb"
fg = "#000006cc"

[app.view]
bg = "#ffffff"
fg = "#000006cc"

[spinner]
color = "#00000670"
size = "16px"
