//! Material theme tokens and loading errors.

mod error;
pub(crate) mod interpolate;
mod opacity;
#[cfg(test)]
mod tests;
/// Typed Material design tokens generated by `spectrum-theme`.
pub mod tokens;

/// Embedded Material 3 light theme.
pub const MATERIAL_LIGHT_TOML: &str = include_str!("../themes/material-light.toml");
/// Embedded Material 3 dark theme.
pub const MATERIAL_DARK_TOML: &str = include_str!("../themes/material-dark.toml");

pub use error::{ThemeLoadError, ThemeSeedError};
pub use opacity::Opacity;
pub use tokens::ThemePack;
